### ISSUE TITLE
How to convert ktx to png?

### ISSUE THREAD

**Issue by zhouhang95** [alexheretic/ktx#1]
As title.

**Comment by alexheretic** [comment]
Ktx is a container for image data encoded for GPUs. So generally you'd go
from a png to ktx as you prepared your art for the gpu. Also note ktx
formats can be lossy compressed which is great for GPUs but not for general
image storage.

With that in mind, getting a png from a ktx means decoding the top level
image data into pixel data (ie 4 byte rgba) and passing that into a png
encoder.

Doing that for uncompressed rgba8 is quite straightforward. GPU compressed
textures are harder.

A general solution is to render the ktx data using opengl/a gpu (ie use the
gpu to decode the data) then read the framebuffer and save/encode that as a
png.

**Comment by zhouhang95** [comment]
tks

**Comment by Kasa-bit** [comment]
easy https://comparecommander.com/online-ktx-to-png-converter/
