### ISSUE TITLE
Cannot access raw image data

### ISSUE THREAD

**Issue by ghost** [alexheretic/ktx#8]
Image data section of ktx files is designed to be directly uploaded to the gpu, allowing users to create an image with a simple memcpy.

libktx example:
 https://github.com/KhronosGroup/Vulkan-Samples/blob/b3e8d49dcc2f94f4a14cafb64f02d1dca71c9565/samples/api/texture_loading/texture_loading.cpp#L150

`Ktx` objects created using this crate do not allow the users to access the raw image data, making this impossible.

**Comment by alexheretic** [comment]
Yeah the API divides texture data into levels, which is what I needed when I wrote it. We could add a method to `Textures` (and/or elsewhere) to return all texture levels as a slice. Maybe raise a pr?
